# Site settings
# {{ site.myvariable }}.

title: Domain Name Search - Kiểm tra tên miền
short_title: Domain Name Search
author: Pham Xuan Tiep
description: >- # this means to ignore newlines
  Kiểm tra tên miền available để đăng ký được hay không .com, .net, .id và vô số định dạng tên miền khác trên thế giới.
keywords: >-
  kiểm tra tên miền, check tên miền, domain, whois domain, domain available, register domain
url: 'https://domain.tiep.vn' # the base hostname & protocol for your site, e.g. http://example.com
baseurl: '' # the subpath of your site, e.g. /blog

# CDN
cdn_url: https://cdn.nomcdn.com/url/cekdomain.js.org
cdn_includeEnvironment: production

# Favicon, manifest, Meta name for Robots
favicon: 'favicon.ico'
manifest: 'manifest.webmanifest'
robots: 'index, follow'
theme-color: '#b22ccf'
# Card data
cardImageSeo: https://cdn.statically.io/og/Domain%20Name%20Search.jpg

# Analytics
umami_websiteId: 5bde902e-c981-44ec-bbd6-e54d9eefeb67
umami_srcUrl: https://owl.nomsad.com/umami.js
umami_trackerConfig: 'data-auto-track="true" data-do-not-track="true"' # https://umami.is/docs/tracker-config
umami_includeEnvironment: production # development or production

# Google Site Verification
google_site_verification: 'codegooglehere'

# Build settings
# theme: minima
plugins:
  - jekyll-sitemap
  - jekyll/minibundle

include: ['.well-known']

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .vscode/
  - LICENSE
  - README.md
  - netlify.toml
  - .prettierignore
  - .gitignore
